# 50-local — machine specific tool initialisers. All of them are guarded: if the
# tool is not installed the block is skipped entirely, so shell startup does not
# slow down or error out.

# ── distrobox / inside a container ───────────────────────────────────────────
if [[ -n "$CONTAINER_ID" || -n "$DISTROBOX_ENTER" ]]; then
  export TERM=xterm-256color
  alias ls='ls --color=auto'
  PS1="%n@%m %1~ %# "
  [ -f /opt/ros/noetic/setup.zsh ] && source /opt/ros/noetic/setup.zsh
  clear
fi

# ── nvm ──────────────────────────────────────────────────────────────────────
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# ── conda / mamba ────────────────────────────────────────────────────────────
# If miniforge3 is not installed the whole block is skipped; without the guard it
# tried to run a non-existent binary on every shell startup.
# The blocks were generated by 'conda init' / 'mamba shell init', do not edit them by hand.
if [ -d "$HOME/miniforge3" ]; then

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$("$HOME/miniforge3/bin/conda" 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "$HOME/miniforge3/etc/profile.d/conda.sh" ]; then
        . "$HOME/miniforge3/etc/profile.d/conda.sh"
    else
        export PATH="$HOME/miniforge3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# >>> mamba initialize >>>
# !! Contents within this block are managed by 'mamba shell init' !!
export MAMBA_EXE="$HOME/miniforge3/bin/mamba";
export MAMBA_ROOT_PREFIX="$HOME/miniforge3";
__mamba_setup="$("$MAMBA_EXE" shell hook --shell zsh --root-prefix "$MAMBA_ROOT_PREFIX" 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__mamba_setup"
else
    alias mamba="$MAMBA_EXE"
fi
unset __mamba_setup
# <<< mamba initialize <<<

fi
