[window]
dynamic_padding = true

[window.padding]
x = 12
y = 12

[colors]
[colors.primary]
background = "#101010"
foreground = "#cdd6f4"

[colors.normal]
black   = "#101010"
red     = "#cf6a4c"
green   = "#8f9d6a"
yellow  = "#f9c74f"
blue    = "#303463"
magenta = "#9a7ecc"
cyan    = "#5de4c7"
white   = "#cdd6f4"

[colors.bright]
black   = "#434343"
red     = "#cf6a4c"
green   = "#8f9d6a"
yellow  = "#f9c74f"
blue    = "#303463"
magenta = "#9a7ecc"
cyan    = "#5de4c7"
white   = "#ffffff"

[colors.cursor]
text   = "#101010"
cursor = "#cdd6f4"

[colors.selection]
text       = "#cdd6f4"
background = "#303463"
